#!/usr/bin/env node

const fs = require('fs')
const path = require('path')

const packageJson = require('./package.json')
const render = require('./README.template')

const eslintVersion = packageJson.dependencies.eslint.replace('^', '')
const configVersion = packageJson.version

const readmePath = path.join(__dirname, 'README.md')
const contents = render(eslintVersion, configVersion)

fs.writeFile(readmePath, contents, 'utf8', (err) => {
  if(err) return console.error('Oh noes', err)
  console.log('Th th thats all folks')
})
